# Generated by Django 3.2.5 on 2021-07-19 18:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Acao',
            fields=[
                ('aco_codigo', models.CharField(max_length=8, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'acao',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cotacao',
            fields=[
                ('cot_data', models.DateField(primary_key=True, serialize=False)),
                ('cot_abertura', models.DecimalField(decimal_places=2, max_digits=6)),
                ('cot_max', models.DecimalField(decimal_places=2, max_digits=6)),
                ('cot_min', models.DecimalField(decimal_places=2, max_digits=6)),
                ('cot_fechamento', models.DecimalField(decimal_places=2, max_digits=6)),
                ('cot_volume', models.IntegerField()),
            ],
            options={
                'db_table': 'cotacao',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CotacaoIndice',
            fields=[
                ('cot_ind_data', models.DateField(primary_key=True, serialize=False)),
                ('cot_ind_abertura', models.DecimalField(decimal_places=2, max_digits=8)),
                ('cot_ind_max', models.DecimalField(decimal_places=2, max_digits=8)),
                ('cot_ind_min', models.DecimalField(decimal_places=2, max_digits=8)),
                ('cot_ind_fechamento', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
            options={
                'db_table': 'cotacao_indice',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('emp_codigo', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('emp_nome', models.CharField(max_length=45, unique=True)),
            ],
            options={
                'db_table': 'empresa',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Indice',
            fields=[
                ('ind_sigla', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('ind_nome', models.CharField(max_length=55, unique=True)),
            ],
            options={
                'db_table': 'indice',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Listagem',
            fields=[
                ('aco_codigo', models.OneToOneField(db_column='aco_codigo', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='stockmonitor.acao')),
                ('list_quantidade', models.BigIntegerField()),
                ('list_percentual', models.DecimalField(decimal_places=3, max_digits=5)),
            ],
            options={
                'db_table': 'listagem',
                'managed': False,
            },
        ),
    ]
